# Generated by Django 5.1.2 on 2024-11-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-number'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
